#!/bin/bash

#vim
sudo add-apt-repository ppa:fcwu-tw/ppa

#tmux
sudo add-apt-repository -y ppa:pi-rho/dev

#node
curl -sL https://deb.nodesource.com/setup_0.10 | sudo -E bash -

#s3cmd
wget -O- -q http://s3tools.org/repo/deb-all/stable/s3tools.key | sudo apt-key add -
wget -O/etc/apt/sources.list.d/s3tools.list http://s3tools.org/repo/deb-all/stable/s3tools.list

sudo apt-get update
sudo apt-get install -y \
  git \
  htop \
  wget \
  curl \
  software-properties-common \
  unzip \
  python \
  make \
  python-pip \
  fontforge \
  ttfautohint \
  exuberant-ctags \
  graphicsmagick \
  vim \
  tmux \
  nodejs \
  s3cmd

#docker
curl -sSL https://get.docker.com/ | sudo sh
sudo usermod -aG docker ubuntu

#docker-compose
curl -L https://github.com/docker/compose/releases/download/1.4.0/docker-compose-`uname -s`-`uname -m` > /usr/local/bin/docker-compose && chmod +x /usr/local/bin/docker-compose

#docker-machine
curl -L https://github.com/docker/machine/releases/download/v0.4.0/docker-machine_linux-amd64 > /usr/local/bin/docker-machine && chmod +x /usr/local/bin/docker-machine

#utf8
sudo locale-gen en_US.UTF-8
export LC_ALL=en_US.utf-8

#Timezone
echo America/Los_Angeles | tee /etc/timezone && dpkg-reconfigure --frontend noninteractive tzdata

#global node libs
npm install -g david grunt-cli bower jscs jshint nodemon aws-cli-utils

#update npm
npm update -g npm

#aws
sudo pip install awscli && sudo pip install awsebcli

#docker-extras
curl -sSL https://raw.githubusercontent.com/jgallen23/docker-extras/master/install.sh | bash

#git-extras
curl -sSL http://git.io/git-extras-setup | bash /dev/stdin

