#!/bin/bash

#vim
sudo add-apt-repository ppa:fcwu-tw/ppa

#tmux
sudo add-apt-repository -y ppa:pi-rho/dev

#node
curl -sL https://deb.nodesource.com/setup_6.x | sudo -E bash -

#mosh
sudo add-apt-repository ppa:keithw/mosh

sudo apt-get update
sudo apt-get install -y \
  git \
  htop \
  wget \
  curl \
  software-properties-common \
  unzip \
  python \
  make \
  python-pip \
  vim \
  tmux \
  nodejs \
  ncdu \
  mosh

#docker
which docker
if [[ "$?" == 1 ]]; then
  curl -sSL https://get.docker.com/ | sudo sh
  sudo usermod -aG docker ubuntu
fi

#docker-compose
DOCKER_COMPOSE_VERSION=1.8.1
sudo curl -L https://github.com/docker/compose/releases/download/$DOCKER_COMPOSE_VERSION/docker-compose-`uname -s`-`uname -m` > /usr/local/bin/docker-compose && sudo chmod +x /usr/local/bin/docker-compose

#utf8
sudo locale-gen en_US.UTF-8
export LC_ALL=en_US.utf-8

#Timezone
echo America/Los_Angeles | sudo tee /etc/timezone && sudo dpkg-reconfigure --frontend noninteractive tzdata

#global node libs
sudo npm install -g david grunt-cli bower nodemon eslint npm-check

#update npm
sudo npm update -g npm

#update pip
sudo pip install --upgrade pip

#aws
sudo pip install awscli && \
  sudo pip install awsebcli && \
  sudo pip install aws-shell

#docker-extras
curl -sSL https://raw.githubusercontent.com/jgallen23/docker-extras/master/install.sh | sudo bash

#git-extras
curl -sSL http://git.io/git-extras-setup | bash /dev/stdin

#httpie
sudo pip install httpie
