#!/bin/bash

apt-get update && \
  apt-get install -y \
    git \
    htop \
    wget \
    curl \
    software-properties-common \
    unzip \
    python \
    make \
    python-pip \
    fontforge \
    ttfautohint \
    exuberant-ctags < /dev/null

#VIM
add-apt-repository ppa:fcwu-tw/ppa && \
  apt-get update && \
  apt-get install -y vim < /dev/null

#TMUX
add-apt-repository -y ppa:pi-rho/dev && \
  apt-get update && \
  apt-get install -y tmux < /dev/null

#node
curl -sL https://deb.nodesource.com/setup_0.10 | sudo -E bash -
apt-get install -y nodejs < /dev/null

#docker
curl -sSL https://get.docker.com/ | sh

#docker-compose
curl -L https://github.com/docker/compose/releases/download/1.4.0/docker-compose-`uname -s`-`uname -m` > /usr/local/bin/docker-compose && chmod +x /usr/local/bin/docker-compose

#docker-machine
curl -L https://github.com/docker/machine/releases/download/v0.4.0/docker-machine_linux-amd64 > /usr/local/bin/docker-machine && chmod +x /usr/local/bin/docker-machine

#utf8
locale-gen en_US.UTF-8
export LC_ALL en_US.utf-8

#Timezone
echo America/Los_Angeles | tee /etc/timezone && dpkg-reconfigure --frontend noninteractive tzdata

#global node libs
npm install -g david grunt-cli bower jscs jshint nodemon aws-cli-utils

#update npm
npm update -g npm

#aws
pip install awscli && pip install awsebcli

#s3cmd
wget -O- -q http://s3tools.org/repo/deb-all/stable/s3tools.key | apt-key add - && \
  wget -O/etc/apt/sources.list.d/s3tools.list http://s3tools.org/repo/deb-all/stable/s3tools.list && \
  apt-get update && \
  apt-get -y install s3cmd < /dev/null

#docker-extras
curl -sSL https://raw.githubusercontent.com/jgallen23/docker-extras/master/install.sh | bash

#git-extras
curl -sSL http://git.io/git-extras-setup | bash /dev/stdin

#dotfiles
if [[ ! -d ~/dotfiles ]]; then
  cd ~
  git clone https://github.com/jgallen23/dotfiles.git
  . dotfiles/bin/dotfiles

  bash ~/dotfiles/vim-install.sh

  ssh-keygen -f ~/.ssh/id_rsa -t rsa -N ''

  echo "Add this to github"
  cat ~/.ssh/id_rsa.pub
fi
