#!/bin/bash

CWD=`pwd`
cd ~
ln -s $CWD/.bash_aliases ~/
ln -s $CWD/.bash_profile ~/
ln -s $CWD/.vim ~/
ln -s $CWD/.vimrc ~/ 
ln -s $CWD/.inputrc ~/
ln -s $CWD/.jshintrc ~/
ln -s $CWD/bin ~/
mkdir -p ~/.config
ln -s $CWD/powerline-config ~/.config/powerline
