#!/bin/bash
CWD=`pwd`
cd ~
echo $CWD
ln -s $CWD/.vim ~/
ln -s $CWD/.vimrc ~/ 
ln -s $CWD/.gitconfig ~/
ln -s $CWD/.bash_aliases ~/
ln -s $CWD/.bash_profile ~/
ln -s $CWD/.jshintrc ~/
ln -s $CWD/.ctags ~/
ln -s $CWD/.tmux.conf ~/
