#!/bin/bash
CWD=`pwd`
cd ~
echo $CWD
ln -s $CWD/.vim ~/
ln -s $CWD/.vimrc ~/ 
ln -s $CWD/.gitconfig ~/
ln -s $CWD/.bash_aliases ~/
ln -s $CWD/.bash_profile ~/
ln -s $CWD/.inputrc ~/
ln -s $CWD/.jshintrc ~/
ln -s $CWD/.ctags ~/
ln -s $CWD/.tmux.conf ~/
ln -s $CWD/bin ~/
ln -s $CWD/.gh.json ~/
rm -rf ~/.nvm
ln -s $CWD/nvm ~/.nvm
