#!/bin/bash

if ! type_exists 'brew'; then
  ruby -e "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/install)"
  brew tap Homebrew/bundle
fi
brew bundle --file=${DOTFILES}/lib/brewfile
