#!/bin/bash
link() {
  # Force create/replace the symlink.
  ln -fs "${DOTFILES}/${1}" "${HOME}/${2}"
}

# Symlinks
link bin bin
link vim .vim
link vim/vimrc .vimrc
link bash/aliases .bash_aliases
link bash/profile .bash_profile
link bash/inputrc .inputrc
link conf/jshintrc .jshintrc
link conf/ctags .ctags
link conf/tmux.conf .tmux.conf
link conf/gitconfig .gitconfig
link conf/gh.json .gh.json
link vendor/nvm .nvm
